#!/bin/bash

if [[ -z "${ASK_API_URL:-}" || -z "${ASK_MODEL:-}" || -z "${ASK_API_KEY:-}" ]]; then
echo "you need to set environment variables. Check README file for more informations"
exit 1
fi

user_input="$*"
stdin_input=""

if [ ! -t 0 ]; then
stdin_input=$(cat)
fi
user_input="$user_input"$'\n'"$stdin_input"


json_payload=$(jq -n \
  --arg model "$ASK_MODEL" \
  --arg content "$user_input" \
  '{
    model: $model,
    messages: [
      {
        role: "system",
        content: "You are a CLI tool. Output plain text only. No yapping. Keep it concise."
      },
      {
        role: "user",
        content: $content
      }
    ]
  }')

response=$(curl -s "$ASK_API_URL" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ASK_API_KEY" \
  -d "$json_payload")

echo "$response" | jq -r '.choices[0].message.content // .error.message'


