#!/bin/bash

if [[ -z "${ASK_API_URL:-}" || -z "${ASK_MODEL:-}" || -z "${ASK_API_KEY:-}"]]; then
echo "you need to set environment variables. Check README file for more informations"
exit 1
fi

user_input="$*"
stdin_input =""

if [ ! -t 0 ]; then
stdin_input=$(cat)
fi
user_input="$user_input"$'\n'"$stdin_input"


response=$(curl -s "$ASK_API_URL" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ASK_API_KEY" \
  -d "{
    \"model\": \"$ASK_MODEL\",
    \"messages\": [
      {
        \"role\": \"system\",
        \"content\": \"You are a CLI tool. Output plain text only.\"
      },
      {
        \"role\": \"user\",
        \"content\": \"$user_input\"
      }
    ]
  }")

